# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'guitar-repair' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for guitar-repair
  pod 'AWSCore', '~> 2.6.1'
  pod 'AWSAuthCore', '~> 2.6.1'
  pod 'AWSCognito', '~> 2.6.1'
  pod 'AWSAPIGateway', '~> 2.6.1'
  pod 'AWSDynamoDB', '~> 2.6.1'
  pod 'AWSPinpoint', '~> 2.6.1'
  pod 'AWSAuthUI', '~> 2.6.1'
  pod 'AWSUserPoolsSignIn', '~> 2.6.1'
  pod 'AWSMobileClient', '~> 2.6.5'
end
